### ISSUE TITLE
Named (incremental) containers

### ISSUE THREAD

**Issue by jeroenj** [mauricioklein/docker-compose-api#13]
Right now docker decides what name a container gets. It would be nice if it was automatically set based on the label attribute. Doing that would obviously require the names to be incremental like how [docker-compose does that](https://github.com/docker/compose/blob/2106481c23429eaf59e653b1bd107c8a809c3cec/compose/service.py#L489-L499).

**Comment by mauricioklein** [comment]
@jeroenj I agree with your suggestion, and I'm working to provide this enhancement as soon as possible.

I'll let you know once the work is done.

Thanks for helping improve this project!

**Comment by mauricioklein** [comment]
@jeroenj It was released a new gem version (1.0.5), with support to container's name on compose file.
You can see an example of such settings on _spec/docker-compose/fixtures/compose_1.yaml_.

If not informed, compose uses container label as container name by default.

Please let me know if you face any issues or miss function in this feature.

Thanks for contributing to project!
