### ISSUE TITLE
docker-compose file v2 (docker-compose v1.6) compatibility

### ISSUE THREAD

**Issue by jeroenj** [mauricioklein/docker-compose-api#21]
Not an urgent one for me, but just adding it as it probably will be needed at some point. Docker-compose 1.6 still supports the _old_ format of the `docker-compose.yml` format.

References:
* https://blog.docker.com/2016/02/compose-1-6/
* https://docs.docker.com/compose/compose-file/#upgrading

**Comment by apeschel** [comment]
:+1:

**Comment by mauricioklein** [comment]
Improvement provided by PR#26.

Thanks to @apeschel for the contribution :+1:

**Comment by jeroenj** [comment]
Cool. :+1:
