### ISSUE TITLE
New release (with docker compose 2 support)?

### ISSUE THREAD

**Issue by ColinHebert** [mauricioklein/docker-compose-api#31]
Would it be possible to get a new release, with the support of docker-compose 2?

**Comment by mauricioklein** [comment]
Yes, sorry about the long delay...
I was in a rush last months....

I'll try to generate a new version this weekand, maximum monday.

Sorry about that!

**Comment by mauricioklein** [comment]
Version 1.1.1 generated, with support to compose v2.
Thanks and sorry about the delay.
