### ISSUE TITLE
Allow editing and saving docker-compose file

### ISSUE THREAD

**Issue by hicham-haouari** [mauricioklein/docker-compose-api#44]
## Description

It would be really great to add to docker-compose-api the ability to edit/save docker-compose files

## How to reproduce

Try to edit/save docker-compose file

## What do you expect

A method to edit, and another to save docker-compose file

## What happened instead

No way to edit/save docker-compose file

## Software:

- Ruby version: ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
- Docker-compose-api gem version: docker-compose-api (1.1.5)

**Comment by mauricioklein** [comment]
I don't agree with this feature.
This gem aims to perform the same functionalities of docker compose, but on Ruby domain.
Since this is not available on original compose library, it makes no sense to add here as well.
Thanks!
